name: run main.py

on:
  schedule:
    - cron: "1 1 * 1 *" # At 01:01 in January
      # '00 14 * * 1-5' # Everyday 11:00 AM on week days

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6' # install the python version needed
          
      - name: Adding locale 
        run: |
            sudo locale-gen tr_TR.UTF-8
            sudo locale-gen tr_TR

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        run: python main.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 